apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flaskvenv
  labels:
    app: flaskvenv
    tier: flaskvenv
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: flaskvenv
  template:
    metadata:
      labels:
        tier: flaskvenv
    spec:
      containers:
      - name: flaskvenv
        image: 177340731096.dkr.ecr.us-east-1.amazonaws.com/flaskvenv:latest
        # imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: flaskvenv
#   name: flaskvenv
#   namespace: default
# spec:
#   externalIPs:
#   - 172.31.106.3
#   - 172.31.153.111
#   - 172.31.175.91
#   ipFamilies:
#   - IPv4
#   ipFamilyPolicy: SingleStack
#   ports:
#   - name: http
#     port: 5001
#     protocol: TCP
#     targetPort: 5000
#   selector:
#     app: flaskvenv
#   sessionAffinity: None
#   type: ClusterIP
